project:
  type: website
  output-dir: docs

website:
  title: "How Data Engineering Powers Data Science: The Architecture of Modern Analytics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



